CREATE TABLE operators (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  prefix CHAR(3) NOT NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  sort INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
