CREATE TABLE orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  number VARCHAR(20) NOT NULL UNIQUE,
  customer_id BIGINT UNSIGNED NOT NULL,
  cargo_type_id BIGINT UNSIGNED NOT NULL,
  from_city VARCHAR(80) NOT NULL,
  from_district VARCHAR(80) NULL,
  from_street VARCHAR(160) NULL,
  from_note VARCHAR(255) NULL,
  from_lat DECIMAL(10,7) NULL,
  from_lng DECIMAL(10,7) NULL,
  to_city VARCHAR(80) NOT NULL,
  to_district VARCHAR(80) NULL,
  to_street VARCHAR(160) NULL,
  to_note VARCHAR(255) NULL,
  to_lat DECIMAL(10,7) NULL,
  to_lng DECIMAL(10,7) NULL,
  date_time DATETIME NOT NULL,
  note TEXT NULL,
  status ENUM('active','waiting','negotiating','closed','cancelled','expired') NOT NULL DEFAULT 'active',
  selected_offer_id BIGINT UNSIGNED NULL,
  expires_at DATETIME NOT NULL,
  reopen_count INT NOT NULL DEFAULT 0,
  slug VARCHAR(24) NOT NULL UNIQUE,
  og_image_path VARCHAR(255) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_customer FOREIGN KEY (customer_id) REFERENCES users(id),
  CONSTRAINT fk_orders_cargo_type FOREIGN KEY (cargo_type_id) REFERENCES cargo_types(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
