CREATE TABLE order_images (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  path VARCHAR(255) NOT NULL,
  thumb_path VARCHAR(255) NOT NULL,
  sort INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_order_images_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
