INSERT INTO settings (skey, svalue) VALUES
  ('subscription_mode', 'free'),
  ('subscription_price', '20'),
  ('subscription_days', '30'),
  ('subscription_currency', 'AZN'),
  ('subscription_activation', 'immediate'),
  ('pin_length', '4'),
  ('session_days', '90'),
  ('order_ttl_hours', '72'),
  ('reminder_intervals', '15,30,60,1440'),
  ('reg_customer_enabled', '1'),
  ('reg_driver_enabled', '1'),
  ('notifications_enabled', '1'),
  ('pwa_prompt_enabled', '1'),
  ('maintenance_mode', '0'),
  ('site_name', 'Yük Birlikdə'),
  ('logo_path', ''),
  ('splash_logo_path', ''),
  ('favicon_path', ''),
  ('whatsapp_number', ''),
  ('contact_phone', ''),
  ('contact_email', ''),
  ('social_links', '{}'),
  ('copyright', '© 2026 Yük.Birlikdə.biz');
